# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sn', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=32)),
            ],
        ),
    ]
